
UnBotCommandRealize = {
[0] = CommandUnBotSetting,
[11] = CommandInspectFrame,
[12] = CommandInitForLevel,
[54] = CommandShowStrategyFrame,
[64] = CommandUnBotItemList,
[65] = CommandUnBotDestroyItem,
[66] = CommandUnBotEquipItem,
[67] = CommandUnBotSellItem,
[68] = CommandUnBotUseItem,
[69] = CommandUnBotSpells,
[70] = CommandCombatStop,
[71] = CommandUninvite,
[72] = CommandListIcons,
[74] = CommandShowOnlineFrame,
[77] = CommandShowNPCFrame,
[78] = CommandFriendsOnline,
[79] = CommandFriendsInvite,
[80] = CommandReadyCheck,
[88] = CommandAddFriends,
};

UnBotCommandToGroups = {
[0] = 0,
[1] = 1,
[2] = 1,
[3] = 1,
[4] = 1,
[5] = 9,
[6] = 9,
[7] = 9,
[8] = 9,
[9] = 9,
[10] = 9,
[11] = 7,
[12] = 1,
[13] = 1,
[14] = 1,
[15] = 2,
[16] = 2,
[17] = 2,
[18] = 2,
[19] = 2,
[20] = 8,
[21] = 8,
[22] = 8,
[23] = 8,
[24] = 2,
[25] = 3,
[26] = 3,
[27] = 3,
[28] = 3,
[29] = 3,
[30] = 3,
[31] = 3,
[32] = 4,
[33] = 4,
[34] = 4,
[35] = 4,
[36] = 4,
[37] = 4,
[38] = 5,
[39] = 5,
[40] = 5,
[41] = 5,
[42] = 5,
[43] = 5,
[44] = 5,
[45] = 5,
[46] = 5,
[47] = 6,
[48] = 6,
[49] = 6,
[50] = 6,
[51] = 6,
[52] = 6,
[53] = 6,
[54] = 8,
[55] = 8,
[56] = 8,
[57] = 8,
[58] = 8,
[59] = 8,
[60] = 8,
[61] = 8,
[62] = 6,
[63] = 6,
[64] = 7,
[65] = 7,
[66] = 7,
[67] = 7,
[68] = 7,
[69] = 8,
[70] = 6,
[71] = 6,
[72] = 10,
[73] = 8,
[74] = 10,
[75] = 6,
[76] = 6,
[77] = 10,
[78] = 10,
[79] = 10,
[80] = 10,
[81] = 7,
[82] = 1,
[83] = 1,
[84] = 9,
[85] = 9,
[86] = 1,
[87] = 1,
[88] = 10,
};

UnBotIconFiles = {
[0] = 5983,
[1] = 514,
[2] = 1177,
[3] = 1178,
[4] = 1287,
[5] = 1125,
[6] = 940,
[7] = 943,
[8] = 938,
[9] = 548,
[10] = 547,
[11] = 4,
[12] = 541,
[13] = 5398,
[14] = 5415,
[15] = 364,
[16] = 369,
[17] = 3006,
[18] = 569,
[19] = 569,
[20] = 928,
[21] = 925,
[22] = 3057,
[23] = 3072,
[24] = 2212,
[25] = 80,
[26] = 85,
[27] = 133,
[28] = 134,
[29] = 112,
[30] = 203,
[31] = 171,
[32] = 81,
[33] = 483,
[34] = 485,
[35] = 304,
[36] = 480,
[37] = 214,
[38] = 5089,
[39] = 4497,
[40] = 399,
[41] = 493,
[42] = 4659,
[43] = 565,
[44] = 301,
[45] = 372,
[46] = 562,
[47] = 523,
[48] = 357,
[49] = 609,
[50] = 5740,
[51] = 325,
[52] = 28,
[53] = 78,
[54] = 5678,
[55] = 5548,
[56] = 5507,
[57] = 5578,
[58] = 5574,
[59] = 5694,
[60] = 5666,
[61] = 5593,
[62] = 817,
[63] = 779,
[64] = 2888,
[65] = 5979,
[66] = 900,
[67] = 4445,
[68] = 3966,
[69] = 3003,
[70] = 3163,
[71] = 169,
[72] = 4662,
[73] = 5946,
[74] = 3513,
[75] = 515,
[76] = 380,
[77] = 598,
[78] = 5982,
[79] = 5639,
[80] = 5974,
[81] = 1758,
[82] = 402,
[83] = 3596,
[84] = 615,
[85] = 2065,
[86] = 74,
[87] = 3598,
[88] = 174,
};

UnBotTooltipTitle = {
[0] = "Close windows and button groups",
[1] = "Initialize all online bots",
[2] = "Initialize a bot",
[3] = "Initialize all bots",
[4] = "Update a random bots",
[5] = "Reset talents of a bot",
[6] = "Add the remaining talents of a bot (1)",
[7] = "Add the remaining talents of a bot (2)",
[8] = "Add the remaining talents of a bot (3)",
[9] = "Reset botAI of all bots",
[10] = "Reset botAI of a bot",
[11] = "Check equipment of a bot",
[12] = "Initialize a bot",
[13] = "Teleport all bots to you",
[14] = "Teleport a bot to you",
[15] = "Make all bots follow you",
[16] = "Make a bot follow you",
[17] = "Make all bots learn spells",
[18] = "Make all bots release spirit",
[19] = "Make a bot release spirit",
[20] = "Check quest status of all bots",
[21] = "Check quest status of a bot",
[22] = "Check the status of all bots",
[23] = "Check the status of a bot",
[24] = "Make all bots collect loot",
[25] = "Make all bots run away",
[26] = "Make tank bots run away",
[27] = "Make dps bots run away",
[28] = "Make healer bots run away",
[29] = "Make melee bots run away",
[30] = "Make ranged bots run away",
[31] = "Make a bot run away",
[32] = "Make all bots attack your target",
[33] = "Make tank bots attack your target",
[34] = "Make dps bots attack your target",
[35] = "Make healer bots attack your target",
[36] = "Make melee bots attack your target",
[37] = "Make ranged bots attack your target",
[38] = "Bot Formation - Arrow",
[39] = "Bot Formation - Defensive",
[40] = "Bot Formation - Dense",
[41] = "Bot Formation - Melee",
[42] = "Bot Formation - Circle",
[43] = "Bot Formation - Lined up",
[44] = "Bot Formation - Queuing",
[45] = "Bot Formation - Hash",
[46] = "Check the formation of all bots",
[47] = "Make all bots stand still",
[48] = "Select bot to automatically select target", -- Needs correction
[49] = "Select bot to select target manually", -- Needs correction
[50] = "Druid Spell DPS", -- Needs correction
[51] = "Druid Bear Form", -- Needs correction
[52] = "Druid Cat Form", -- Needs correction
[53] = "Druid Healing Mode", -- Needs correction
[54] = "Open the strategy editor",
[55] = "Make a Paladin bot use Frost Resistance Aura",
[56] = "Make a Paladin bot use Fire Resistance Aura",
[57] = "Make a Paladin bot use Devotion Aura",
[58] = "Make a Paladin bot use Crusader Aura",
[59] = "Make a Paladin bot use Blessing of Kings",
[60] = "Make a Paladin bot use Blessing of Wisdom",
[61] = "Make a Paladin bot use Blessing of Might",
[62] = "Check AI status of all bots",
[63] = "Check AI status of a bot",
[64] = "Check inventory of a bot",
[65] = "Make a bot discard an item",
[66] = "Check equipment of a bot",
[67] = "Make a bot sell an item",
[68] = "Make a bot use an item",
[69] = "Check spell book of a bot",
[70] = "Make the entire group leave combat",
[71] = "Disband the group",
[72] = "View all icons in the game",
[73] = "Teleport to another player",
[74] = "Manage bots",
[75] = "See non-combat strategies for selecting bots", -- Needs correction
[76] = "Make a bot stand still",
[77] = "Summon a bot",
[78] = "Make all bots on your friends list go online",
[79] = "Invite everyone on your friends list",
[80] = "Check in place", -- Needs correction
[81] = "Make all bots restore mana",
[82] = "Make all bots go offline",
[83] = "Make all bots go online",
[84] = "Module: Naxxramas",
[85] = "Reset actions for all bots",
[86] = "Make a bot go offline",
[87] = "Make a bot go online",
[88] = "Add all bots to your friends list",
};

UnBotTooltipHelp = {
[0] = "Closes open windows and expanded button groups. Use right mouse button to hide the bar. You can use /unbot to toggle the bar.",
[1] = "Reinitialize all online bots, including their levels (random among the level ranges set), equipment, and skills. After execution, the server will be stuck and you need to wait. It cannot be executed frequently.", -- Needs correction
[2] = "Initializes the targeted bot. It will set their level, equipment, and skills.",
[3] = "Initializes all bots in your group. It will set their level, equipment, and skills.",
[4] = "Update random bots. When the number of online bots is not enough for the background setting, supplementary bots will be online. When the quantity is sufficient, some will be offline and some will be online.", -- Needs correction
[5] = "Select the bot to reset its talents, and then use the bots command to add the remaining talents to allow the bot to switch talents. If the bot switches talents, you need to execute reset ai again to make the bot work in the new talents (Command No. 9 or 10). You need a GM account to be valid.", -- Needs correction
[6] = "Select the bot and let it add all remaining talent points to its talents on the first type page. If the bot switches talents, you need to execute reset ai again to make the bot work in the new talent (Command No. 9 or 10 reset ai).", -- Needs correction
[7] = "Select the bot and let it add all remaining talent points to its talents on the second type page. If the bot switches talents, you need to execute reset ai again to make the bot work in the new talent (Command No. 9 or 10 reset ai).", -- Needs correction
[8] = "Select the bot and let it add all remaining talent points to the talent on its third type page. If the bot switches talents, you need to execute reset ai again to make the bot work in the new talent (Command No. 9 or 10 reset ai).", -- Needs correction
[9] = "Reset the AI ​​strategy of all bots in the team. After a bot switches talents, it is usually necessary to execute this command so that the bots can start fighting with new talents.", -- Needs correction
[10] = "Reset the AI ​​strategy of the selected bot. After the bot switches talents, you usually need to execute this command to let the bot start fighting with the new talents.", -- Needs correction
[11] = "Open the bot equipment interface. On each equipment slot, left-click the mouse to change the bots equipment, and right-click the mouse to remove the bots equipment. (Only valid for bots in the team)", -- Needs correction
[12] = "Initialize the target bot to your own level, and reset its skills and equipment to this level. If you want to reset it to another level, you need to manually enter the command, and finally add the level number.", -- Needs correction
[13] = "Teleports all bots in your group to you.",
[14] = "Teleports the targeted bot to you.",
[15] = "Makes all bots in your group follow you in the set formation. They will continue their normal routine while in combat. It will also stop the bots from fleeing if the run away command was used.",
[16] = "Makes the targeted bot follow you. It is especially useful to stop the bot from fleeing if the run away command was used.",
[17] = "Let the bots in the entire team learn the skills they can learn from the selected trainer NPC, including class trainers and profession trainers. If the correct NPC is not selected, it will be ineffective.", -- Needs correction
[18] = "Let all the dead bots in the team release their souls (then you can use the summon-teleport command to resurrect the bots to you, command 13 or 14 summon). This command only applies to dungeons.", -- Needs correction
[19] = "Have the selected bot release its soul if it is already dead, otherwise it has no effect. (You can then use the summon-teleport command to revive the bot to your side, Command No. 13 or 14 summon). This command only applies to dungeons.", -- Needs correction
[20] = "Checks the quest status of all bots in your group. It will tell you how many quests are completed and how many are in progress.",
[21] = "Checks the quest status of the targeted bot. It will tell you how many quests are completed and how many are in progress.",
[22] = "View the current status of all bots in the team, including: what percentage of experience the current level has, the number of remaining backpack slots, and the amount of remaining money.", -- Needs correction
[23] = "View the current status of the selected bot, including: what percentage of experience the current level has, the number of remaining backpack grids, and the amount of remaining money.", -- Needs correction
[24] = "Makes all bots in your group collect loot from all nearby dead enemies.",
[25] = "Makes all bots in the team run away, abandon the fight, and run to your own location to follow you. (You can use the follow command to cancel this effect, command 15 or 16 follow)", -- Needs correction
[26] = "Let the tank robot in the team run away, give up the fight, and run to your own position to follow you. (You can use the follow command to cancel this effect, command 15 or 16 follow)", -- Needs correction
[27] = "Let the dps robot in the team run away, give up the fight, and run to your own position to follow you. (You can use the follow command to cancel this effect, command 15 or 16 follow)", -- Needs correction
[28] = "Have the healer bots in the team run away, give up the fight, and run to your own location to follow you. (You can use the follow command to cancel this effect, command 15 or 16 follow)", -- Needs correction
[29] = "Let the melee bots in the team run away, give up the fight, and run to your own position to follow you. (You can use the follow command to cancel this effect, command 15 or 16 follow)", -- Needs correction
[30] = "Let the ranged bots in the team run away, give up the fight, and run to your own location to follow you. (You can use the follow command to cancel this effect, command 15 or 16 follow)", -- Needs correction
[31] = "Makes the chosen bot escape, give up the fight, and run to your own location to follow you. (You can use the follow command to cancel this effect, command 15 or 16 follow)", -- Needs correction
[32] = "Makes all bots in your group attack the targeted enemy.",
[33] = "Makes tank bots in your group attack the targeted enemy.",
[34] = "Makes dps bots in your group attack the targeted enemy.",
[35] = "Makes healer bots in your group attack the targeted enemy.",
[36] = "Makes melee bots in your group attack the targeted enemy.",
[37] = "Makes ranged bots in your group attack the targeted enemy.",
[38] = "Makes all bots in your group position themselves in the shape of an arrow. In the front are tanks followed by melee dps, ranged dps, and healers at the end.",
[39] = "Makes all bots in your group position themselves in a defensive formation.",
[40] = "Makes all bots in your group position themselves in a dense formation.",
[41] = "Let all bots in the team position themselves according to the melee mode.", -- Needs correction
[42] = "Let all the bots in the team stand in a circular shape, with tanks and melee in the middle, and ranged and healers standing in a large circle on the outside.", -- Needs correction
[43] = "Let all the bots in the team stand in the shape of a phalanx, just like the phalanx on the ancient Roman battlefield.", -- Needs correction
[44] = "Let all the bots in the team move with you one by one. After the first movement is completed, the second one starts to move and spread out their positions.", -- Needs correction
[45] = "Let all the bots in the team spread out and follow you one by one.", -- Needs correction
[46] = "Checks the current formation of all bots in your group.",
[47] = "The whole team stops moving and stands still. They perform their duties after entering the battle. They continue to stand still after exiting the battle.", -- Needs correction
[48] = "Select the bot to automatically select the target. Once entering the battle, the bot will automatically select the attack target. The attack command is invalid for the bot.", -- Needs correction
[49] = "Select the bot to manually select the target. After entering the battle, the bot will be manually selected by the player to attack the designated target. It will not switch automatically. In other words, the DPS and TANK strategies are invalid in this combat mode, and the attack command is valid for the bot.", -- Needs correction
[50] = "The selected druid bot uses spell dps in combat, and uses it if it has a moonkin form.", -- Needs correction
[51] = "The selected druid bot uses bear or giant bear form to pull monsters during battle.", -- Needs correction
[52] = "Use cat form dps in selected druid bot battles.", -- Needs correction
[53] = "The selected druid bot is in healing mode during combat.", -- Needs correction
[54] = "Open the strategy editor window and make detailed settings for the selected bots combat and non-combat strategies.", -- Needs correction
[55] = "Makes the targeted Paladin bot use Frost Resistance Aura.",
[56] = "Makes the targeted Paladin bot use Fire Resistance Aura.",
[57] = "Makes the targeted Paladin bot use Devotion Aura.",
[58] = "Makes the targeted Paladin bot use Crusader Aura.",
[59] = "Makes the targeted Paladin bot use Blessing of Kings to buff other members of your group.",
[60] = "Makes the targeted Paladin bot use Blessing of Wisdom to buff other members of your group.",
[61] = "Makes the targeted Paladin bot use Blessing of Might to buff other members of your group.",
[62] = "Checks the AI status of all bots in your group.",
[63] = "Checks the AI status of the targeted bot.",
[64] = "Open the View Props window and list all the props in the current backpack of the selected bot for you to view. If you need to discard, equip or use these props, please use the following commands. (|cffbb0000 When the bots backpack changes due to other reasons, this window will not change synchronously. You need to manually click the refresh button to synchronize. The refresh button and all prop buttons are invalid while the bot is sitting on the floor, eating, drinking, and casting spells|r)", -- Needs correction
[65] = "Open the discard props window, which lists all the props in the current backpack of the selected bot for you to view. Left-click on a prop to let the bot discard it, and right-click on a prop to hide it. (|cffbb0000 When the bots backpack changes due to other reasons, this window will not change synchronously. You need to manually click the refresh button to synchronize. The refresh button and all prop buttons are invalid while the bot is sitting on the floor, eating, drinking, and casting spells.|r)", -- Needs correction
[66] = "Open the equipment and props window, which lists all the props in the current backpack of the selected bot for you to view. Left-click on a prop to let the bot equip it, and right-click on a prop to hide it. (|cffbb0000 When the bots backpack changes due to other reasons, this window will not change synchronously. You need to manually click the refresh button to synchronize. The refresh button and all prop buttons are invalid while the bot is sitting on the floor, eating, drinking, and casting spells.|r)", -- Needs correction
[67] = "Open the Sell Props window, which lists all the props in the current backpack of the selected bot for you to view. Left-click on an prop to let the bot sell it to the merchant you currently selected. Right-click on an prop to hide it. (|cffbb0000 When the bots backpack changes due to other reasons, this window will not change synchronously. You need to manually click the refresh button to synchronize. The refresh button and all prop buttons are invalid while the bot is sitting on the floor, eating, drinking, and casting spells.|r)", -- Needs correction
[68] = "Open the Use Props window, which lists all the props in the current backpack of the selected bot for you to view. Left-click on a prop to let the bot use it for its current target. Right-click on a prop to hide it. (|cffbb0000 When the bots backpack changes due to other reasons, this window will not change synchronously. You need to manually click the refresh button to synchronize. The refresh button and all prop buttons are invalid while the bot is sitting on the floor, eating, drinking, and casting spells.|r)", -- Needs correction
[69] = "Open the skills window and list the combat skills and non-combat skills owned by the selected bot. You can left-click the skill in the window to let the bot cast it. Right-click the skill to hide the skill. The skill you cast may have target requirements. You need to select the correct one before clicking. The target cannot be selected without the target's skills. (|cffbb0000 When the skills owned by the bot change due to other reasons, this window will not change synchronously. You need to manually click the refresh button to synchronize. The refresh button and all skill buttons are invalid while the bot is sitting on the floor, eating, drinking, and casting spells.|r)", -- Needs correction
[70] = "Makes everyone in you group, including yourself, leave combat. (GM only)",
[71] = "Let all players in the team leave the team, and the bots can leave the team one by one to avoid being unable to form these bots after you leave the team.", -- Needs correction
[72] = "Opens a window that lists all icons available in World of Warcraft.",
[73] = "Teleports you to the targeted player. (GM only)",
[74] = "Opens a window that shows all bots on your friends list and in your guild. The left mouse button will make a bot go online while right mouse button will invite it to your group.",
[75] = "See non-combat strategies for selecting bots", -- Needs correction
[76] = "Makes a bot stand still. It can still continue its normal routine while in combat but will return to standing still after leaving combat.",
[77] = "Opens a window that allows you to summon a bot.",
[78] = "Makes all bots on your friends list go online.",
[79] = "Invites everyone on your friends list to your group. If the group is full while invites are still happening the process will be aborted.",
[80] = "Execute a team's position confirmation and let the bot automatically replenish food, drink, ammunition and arrows according to the situation.", -- Needs correction
[81] = "Makes all bots in your group drink water to restore mana.",
[82] = "Makes all bots in your group go offline.",
[83] = "Makes all bots in your group go online.",
[84] = "Enables the Naxxramas module for all bots in your group. This is only usable while inside Naxxramas.",
[85] = "Resets actions for all bots in your group.",
[86] = "Makes the targeted bot go offline.",
[87] = "Makes the targeted bot go online.",
[88] = "Adds all bots in your group to your friends list."
};

UnBotExecuteCommand = {
[1] = "",
[2] = ".playerbot bot init=epic",
[3] = ".playerbot bot init=epic *",
-- [4] = ".playerbot bot update",
[5] = ".reset talents",
-- [6] = ".playerbot bot talent=1",
-- [7] = ".playerbot bot talent=2",
-- [8] = ".playerbot bot talent=3",
[9] = "reset botAI",--/p
[10] = "reset botAI",--/w %s 
[11] = "inspect",--/w %s
-- [12] = ".playerbot bot initforlevel ",
[13] = "summon",--/p
[14] = "summon",--/w %s 
[15] = "follow",--/p
[16] = "follow",--/w %s 
[17] = "trainer learn",--/p
[18] = "release",--/p
[19] = "release",--/w %s 
[20] = "quests",--/p
[21] = "quests",--/w %s 
[22] = "stats",--/p
[23] = "stats",--/w %s 
[24] = "add all loot",--/p
[25] = "flee",--/p
[26] = "@tank flee",--/p
[27] = "@dps flee",--/p
[28] = "@heal flee",--/p
[29] = "@melee flee",--/p
[30] = "@ranged flee",--/p
[31] = "flee",--/w %s 
[32] = "attack",--/p
[33] = "@tank attack",--/p
[34] = "@dps attack",--/p
[35] = "@heal attack",--/p
[36] = "@melee attack",--/p
[37] = "@ranged attack",--/p
[38] = "formation arrow",--/p
[39] = "formation queue",--/p
[40] = "formation near",--/p
[41] = "formation melee",--/p
[42] = "formation line",--/p
[43] = "formation circle",--/p
[44] = "formation chaos",--/p
[45] = "formation shield",--/p
[46] = "formation",--/p
[47] = "stay",--/p
[48] = "",--/w %s 
[49] = "",--/w %s 
[50] = "",--/w %s 
[51] = "",--/w %s 
[52] = "",--/w %s 
[53] = "",--/w %s 
[54] = "strategy",--/w %s 
[55] = "",--/w %s 
[56] = "",--/w %s 
[57] = "",--/w %s 
[58] = "",--/w %s 
[59] = "",--/w %s 
[60] = "",--/w %s 
[61] = "",--/w %s 
[62] = "",--/p
[63] = "",--/w %s 
[64] = "c",--/w %s 
[65] = "destroy ",--/w %s 
[66] = "e ",--/w %s 
[67] = "s ",--/w %s 
[68] = "u ",--/w %s 
[69] = "cast ",--/w %s 
-- [70] = ".combatstop ",--/p
[71] = "UninviteUnit ",--/p
[72] = "ICONS",
[73] = ".appear",
[74] = "online",
[75] = "",--/w %s 
[76] = "stay",--/w %s 
[77] = ".playerbot bot addclass",
[78] = "friends online",
[79] = "friends invite",
-- [80] = "ready check",
[81] = "drink",
[82] = ".playerbot bot remove *",
[83] = ".playerbot bot add *",
[84] = "naxx",
[85] = "reset",
[86] = ".playerbot bot remove",
[87] = ".playerbot bot add",
-- [88] = "add friends"
};

--1 = 不需要选择目标
--2 = 需要选择友方目标
--3 = 需要选择敌对目标"
--4 = 自动以全队作为目标
UnBotCommandType = {
[0] = 0,
[1] = 1,
[2] = 2,
[3] = 1,
[4] = 1,
[5] = 2,
[6] = 2,
[7] = 2,
[8] = 2,
[9] = 4,
[10] = 2,
[11] = 2,
[12] = 2,
[13] = 4,
[14] = 2,
[15] = 4,
[16] = 2,
[17] = 4,
[18] = 4,
[19] = 2,
[20] = 4,
[21] = 2,
[22] = 4,
[23] = 2,
[24] = 4,
[25] = 4,
[26] = 4,
[27] = 4,
[28] = 4,
[29] = 4,
[30] = 4,
[31] = 2,
[32] = 3,
[33] = 3,
[34] = 3,
[35] = 3,
[36] = 3,
[37] = 3,
[38] = 4,
[39] = 4,
[40] = 4,
[41] = 4,
[42] = 4,
[43] = 4,
[44] = 4,
[45] = 4,
[46] = 4,
[47] = 4,
[48] = 2,
[49] = 2,
[50] = 2,
[51] = 2,
[52] = 2,
[53] = 2,
[54] = 2,
[55] = 2,
[56] = 2,
[57] = 2,
[58] = 2,
[59] = 2,
[60] = 2,
[61] = 2,
[62] = 4,
[63] = 2,
[64] = 2,
[65] = 2,
[66] = 2,
[67] = 2,
[68] = 2,
[69] = 2,
[70] = 4,
[71] = 4,
[72] = 1,
[73] = 1,
[74] = 1,
[75] = 2,
[76] = 2,
[77] = 1,
[78] = 1,
[79] = 1,
[80] = 1,
[81] = 4,
[82] = 1,
[83] = 1,
[84] = 4,
[85] = 4,
[86] = 2,
[87] = 2,
[88] = 4,
};
